services:
  strapi:
    container_name: rbc_strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: rbc-strapi:latest
    restart: unless-stopped
    ports:
      - '1337:1337'
    volumes:
      - ./.tmp:/opt/app/.tmp
      - ./public/uploads:/opt/app/public/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=493ea119ea551227ae136237d6af5d4d,7160cd1b03054f778b87d5c7b414e768
      - API_TOKEN_SALT=7b3926d1f71344ef7e427dc39da1b5ff583
      - ADMIN_JWT_SECRET=e6bc23a9fc083e33b63db0d3bbfeda7a
      - TRANSFER_TOKEN_SALT=14d11f028dca90d8dfc7f4eb93bdc47
      - JWT_SECRET=3f5bf49a5c3a4953b3598532fabee2af
      - ENCRYPTION_KEY=1781251449067342003RajWanchooB
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - NODE_ENV=production
