version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: rbc-strapi:latest
    restart: unless-stopped
    expose:
      - '3000'
    labels:
      - "traefik.docker.network=dokploy-network"
    volumes:
      - strapi_db_volume:/opt/app/database
      - strapi_uploads_volume:/opt/app/public/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=database/data.db
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000/admin"]
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dokploy-network

volumes:
  strapi_db_volume:
  strapi_uploads_volume:

networks:
  dokploy-network:
    external: true
