services:
  strapi:
    container_name: rbc_strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: rbc-strapi:latest
    restart: unless-stopped
    ports:
      - '1337:1337'
    volumes:
      - ./.tmp:/opt/app/.tmp
      - ./public/uploads:/opt/app/public/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - NODE_ENV=production
